go:
    # Whenever the Go version is updated here, .circle/config.yml and Dockerfile should also be updated.
    version: 1.23
repository:
    path: github.com/tynany/frr_exporter
build:
    binaries:
        - name: frr_exporter
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}

crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - linux/arm
        - linux/arm64
        - darwin/amd64
        - darwin/arm
        - darwin/arm64
        - freebsd/amd64
        - freebsd/386
        - freebsd/arm
        - freebsd/arm64
